name: setup-node
description: https://github.com/actions/setup-node
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - shell: bash
      run: yarn --immutable
