#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

storage: ./storage
plugins: ./plugins

middlewares:
  passport-google-oauth-ui:
    enabled: true

auth:
  passport-google-oauth-ui:
    client-id: GITHUB_CLIENT_ID # required
    client-secret: GITHUB_CLIENT_SECRET # required
    enabled: true
  htpasswd:
    file: ./htpasswd

security:
  api:
    jwt:
      sign:
        expiresIn: 90d
  web:
    sign:
      expiresIn: 7d

packages:
  "@*/*":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  "**":
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
